[xdebug]
; Включение Xdebug
xdebug.mode=debug
; Автоматический запуск отладки (опционально)
xdebug.start_with_request=trigger
; Порт для отладки
xdebug.client_port=9003
; Хост для отладки (замените на IP вашей IDE)
xdebug.client_host=host.docker.internal
; Логирование Xdebug
;xdebug.log=/var/log/php/xdebug.log
;xdebug.log_level=0
; Улучшенное отображение переменных
xdebug.show_local_vars=0
; Максимальная глубина вложенности
xdebug.max_nesting_level=512
; Включение трассировки
;xdebug.trace_output_dir=/var/log/php
; Включение профилирования
;xdebug.profiler_output_dir=/var/log/php
; Идентификатор сессии (для разделения логов)
xdebug.idekey=PhpStorm